import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import db from '@/lib/db';
const API_BASE = 'https://api.taxi4u.cab';

async function getAuthToken(): Promise<string> {
  const loginResponse = await fetch(`${API_BASE}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      userId: process.env.TAXI4U_USERNAME,
      password: process.env.TAXI4U_PASSWORD,
    }),
  });

  if (!loginResponse.ok) {
    throw new Error(`Auth failed: ${loginResponse.status}`);
  }

  const loginData = await loginResponse.text();
  return loginData.replace(/['"]+/g, '');
}
export async function GET(request: Request) {
  try {
    // 1. Get all pending receipt requests
    const stmt = db.prepare(`SELECT * FROM receipt_requests WHERE status = 'pending'`);
    const pendingRequests = stmt.all() as {
      id: number;
      bookingId: string;
      email: string;
      status: string;
      timestamp: number;
    }[];

    if (pendingRequests.length === 0) {
      return NextResponse.json({ message: 'No pending receipts' });
    }

    const authToken = await getAuthToken();
    let processed = 0;
    let sent = 0;

    // Set up nodemailer transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || '',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER || '',
        pass: process.env.SMTP_PASS || '',
      },
    });

    for (const req of pendingRequests) {
      processed++;
      try {
        // We use centralCode=VS, you might want this configurable
        const centralCode = 'VS';
        const url = `${API_BASE}/api/receipt?centralCode=${centralCode}&bookRef=${req.bookingId}`;
        
        const response = await fetch(url, {
          headers: {
            'Authorization': `Bearer ${authToken}`
          }
        });

        if (response.status === 404) {
          // Trip not completed or receipt not ready yet
          console.log(`Receipt not ready yet for booking: ${req.bookingId}`);
          continue;
        }

        if (!response.ok) {
          console.error(`Error fetching receipt for ${req.bookingId}: ${response.status}`);
          continue;
        }

        const receiptData = await response.json();
        
        const lang = req.language || 'no';
        const t = {
          no: {
            title: 'Kvittering for din tur',
            thanks: 'Takk for at du reiste med oss!',
            date: 'Dato for tur:',
            booking: 'Bookingnummer:',
            from: 'Fra:',
            to: 'Til:',
            distance: 'Distanse:',
            notProvided: 'Ikke oppgitt',
            priceExVat: 'Pris uten MVA:',
            vat: 'MVA',
            total: 'Totalpris:',
            autoGenerated: 'Dette er en automatisk generert kvittering.',
            subject: `Kvittering for din tur med Voss Taxi (${req.bookingId})`
          },
          en: {
            title: 'Receipt for your trip',
            thanks: 'Thank you for traveling with us!',
            date: 'Trip date:',
            booking: 'Booking number:',
            from: 'From:',
            to: 'To:',
            distance: 'Distance:',
            notProvided: 'Not provided',
            priceExVat: 'Price ex. VAT:',
            vat: 'VAT',
            total: 'Total price:',
            autoGenerated: 'This is an automatically generated receipt.',
            subject: `Receipt for your trip with Voss Taxi (${req.bookingId})`
          },
          de: {
            title: 'Quittung für Ihre Fahrt',
            thanks: 'Danke, dass Sie mit uns gereist sind!',
            date: 'Fahrtdatum:',
            booking: 'Buchungsnummer:',
            from: 'Von:',
            to: 'Nach:',
            distance: 'Entfernung:',
            notProvided: 'Nicht angegeben',
            priceExVat: 'Preis exkl. MwSt:',
            vat: 'MwSt',
            total: 'Gesamtpreis:',
            autoGenerated: 'Dies ist eine automatisch generierte Quittung.',
            subject: `Quittung für Ihre Fahrt mit Voss Taxi (${req.bookingId})`
          },
          es: {
            title: 'Recibo de su viaje',
            thanks: '¡Gracias por viajar con nosotros!',
            date: 'Fecha del viaje:',
            booking: 'Número de reserva:',
            from: 'Desde:',
            to: 'Hasta:',
            distance: 'Distancia:',
            notProvided: 'No proporcionado',
            priceExVat: 'Precio sin IVA:',
            vat: 'IVA',
            total: 'Precio total:',
            autoGenerated: 'Este es un recibo generado automáticamente.',
            subject: `Recibo de su viaje con Voss Taxi (${req.bookingId})`
          },
          fr: {
            title: 'Reçu pour votre trajet',
            thanks: 'Merci d\'avoir voyagé avec nous !',
            date: 'Date du trajet:',
            booking: 'Numéro de réservation:',
            from: 'De:',
            to: 'À:',
            distance: 'Distance:',
            notProvided: 'Non fourni',
            priceExVat: 'Prix HT:',
            vat: 'TVA',
            total: 'Prix total:',
            autoGenerated: 'Ceci est un reçu généré automatiquement.',
            subject: `Reçu pour votre trajet avec Voss Taxi (${req.bookingId})`
          },
          nn: {
            title: 'Kvittering for turen din',
            thanks: 'Takk for at du reiste med oss!',
            date: 'Dato for tur:',
            booking: 'Bookingnummer:',
            from: 'Frå:',
            to: 'Til:',
            distance: 'Distanse:',
            notProvided: 'Ikkje oppgjeve',
            priceExVat: 'Pris utan MVA:',
            vat: 'MVA',
            total: 'Totalpris:',
            autoGenerated: 'Dette er ei automatisk generert kvittering.',
            subject: `Kvittering for turen din med Voss Taxi (${req.bookingId})`
          }
        }[lang] || { title: 'Kvittering for din tur', thanks: 'Takk for at du reiste med oss!', date: 'Dato for tur:', booking: 'Bookingnummer:', from: 'Fra:', to: 'Til:', distance: 'Distanse:', notProvided: 'Ikke oppgitt', priceExVat: 'Pris uten MVA:', vat: 'MVA', total: 'Totalpris:', autoGenerated: 'Dette er en automatisk generert kvittering.', subject: `Kvittering for din tur med Voss Taxi (${req.bookingId})` };

        // Build an elegant HTML email
        const htmlContent = `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #f59e0b;">
              <h1 style="margin: 0; color: #1f2937;">Voss Taxi</h1>
              <p style="margin: 5px 0; color: #6b7280;">${t.title}</p>
            </div>
            
            <div style="padding: 20px 0;">
              <p>${t.thanks}</p>
              
              <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                <tr>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${t.date}</td>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; text-align: right;">${new Date(receiptData.startDateTime).toLocaleDateString(lang === 'no' || lang === 'nn' ? 'no-NO' : lang === 'en' ? 'en-US' : lang + '-' + lang.toUpperCase())}</td>
                </tr>
                <tr>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${t.booking}</td>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; text-align: right;">${receiptData.bookRef || req.bookingId}</td>
                </tr>
                <tr>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${t.from}</td>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; text-align: right;">${receiptData.fromAddress || t.notProvided}</td>
                </tr>
                <tr>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${t.to}</td>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; text-align: right;">${receiptData.toAddress || t.notProvided}</td>
                </tr>
                <tr>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">${t.distance}</td>
                  <td style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; text-align: right;">${receiptData.km} km</td>
                </tr>
              </table>

              <table style="width: 100%; border-collapse: collapse; margin-top: 20px; background-color: #f9fafb; border-radius: 8px;">
                <tr>
                  <td style="padding: 15px; color: #6b7280;">${t.priceExVat}</td>
                  <td style="padding: 15px; text-align: right;">${receiptData.vatBasis?.toFixed(2)} kr</td>
                </tr>
                <tr>
                  <td style="padding: 15px; color: #6b7280;">${t.vat} (${receiptData.vatPercentage}%):</td>
                  <td style="padding: 15px; text-align: right;">${receiptData.vat?.toFixed(2)} kr</td>
                </tr>
                <tr>
                  <td style="padding: 15px; font-weight: bold; font-size: 1.1em; border-top: 2px solid #e5e7eb;">${t.total}</td>
                  <td style="padding: 15px; font-weight: bold; font-size: 1.1em; text-align: right; border-top: 2px solid #e5e7eb;">${receiptData.total?.toFixed(2)} kr</td>
                </tr>
              </table>
            </div>

            <div style="text-align: center; padding-top: 30px; color: #9ca3af; font-size: 0.9em;">
              <p>Voss Taxi - Org.nr: ${receiptData.vatRegistrationNo || '970 148 642 MVA'}</p>
              <p>${t.autoGenerated}</p>
            </div>
          </div>
        `;

        const mailOptions = {
          from: process.env.SMTP_FROM || 'no-reply@vosstaxi.no',
          to: req.email,
          subject: t.subject,
          html: htmlContent,
        };

        await transporter.sendMail(mailOptions);
        
        // Update DB
        const updateStmt = db.prepare(`UPDATE receipt_requests SET status = 'sent' WHERE id = ?`);
        updateStmt.run(req.id);
        
        sent++;
        console.log(`✅ Sent receipt to ${req.email} for booking ${req.bookingId}`);

      } catch (err) {
        console.error(`❌ Failed to process receipt for booking ${req.bookingId}:`, err);
      }
    }

    return NextResponse.json({ message: 'Processed', processed, sent });
  } catch (error) {
    console.error('CRON ERROR:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
