import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import db from '@/lib/db';
const API_BASE = 'https://api.taxi4u.cab';

async function getAuthToken(): Promise<string> {
  const loginResponse = await fetch(`${API_BASE}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      userId: process.env.TAXI4U_USERNAME,
      password: process.env.TAXI4U_PASSWORD,
    }),
  });

  if (!loginResponse.ok) {
    throw new Error(`Auth failed: ${loginResponse.status}`);
  }

  const loginData = await loginResponse.text();
  return loginData.replace(/['"]+/g, '');
}
export async function GET() {
  try {
    // 1. Get all pending receipt requests
    const stmt = db.prepare(`SELECT * FROM receipt_requests WHERE status = 'pending'`);
    const pendingRequests = stmt.all() as {
      id: number;
      bookingId: string;
      email: string;
      language: string;
      status: string;
      timestamp: number;
    }[];

    if (pendingRequests.length === 0) {
      return NextResponse.json({ message: 'No pending receipts' });
    }

    const authToken = await getAuthToken();
    let processed = 0;
    let sent = 0;

    // Set up nodemailer transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || '',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER || '',
        pass: process.env.SMTP_PASS || '',
      },
    });

    for (const req of pendingRequests) {
      processed++;
      try {
        // We use centralCode=VS, you might want this configurable
        const centralCode = 'VS';
        const url = `${API_BASE}/api/receipt?centralCode=${centralCode}&bookRef=${req.bookingId}`;
        
        const response = await fetch(url, {
          headers: {
            'Authorization': `Bearer ${authToken}`
          }
        });

        if (response.status === 404) {
          // Trip not completed or receipt not ready yet
          console.log(`Receipt not ready yet for booking: ${req.bookingId}`);
          continue;
        }

        if (!response.ok) {
          console.error(`Error fetching receipt for ${req.bookingId}: ${response.status}`);
          continue;
        }

        const receiptData = await response.json();
        
        const lang = req.language || 'no';
        const t = {
          no: {
            title: 'Kvittering for din tur',
            thanks: 'Takk for at du reiste med oss!',
            date: 'Dato for tur:',
            booking: 'Bookingnummer:',
            from: 'Fra:',
            to: 'Til:',
            distance: 'Distanse:',
            notProvided: 'Ikke oppgitt',
            priceExVat: 'Pris uten MVA:',
            vat: 'MVA',
            total: 'Totalpris:',
            autoGenerated: 'Dette er en automatisk generert kvittering.',
            subject: `Kvittering for din tur med Voss Taxi (${req.bookingId})`
          },
          en: {
            title: 'Receipt for your trip',
            thanks: 'Thank you for traveling with us!',
            date: 'Trip date:',
            booking: 'Booking number:',
            from: 'From:',
            to: 'To:',
            distance: 'Distance:',
            notProvided: 'Not provided',
            priceExVat: 'Price ex. VAT:',
            vat: 'VAT',
            total: 'Total price:',
            autoGenerated: 'This is an automatically generated receipt.',
            subject: `Receipt for your trip with Voss Taxi (${req.bookingId})`
          },
          de: {
            title: 'Quittung für Ihre Fahrt',
            thanks: 'Danke, dass Sie mit uns gereist sind!',
            date: 'Fahrtdatum:',
            booking: 'Buchungsnummer:',
            from: 'Von:',
            to: 'Nach:',
            distance: 'Entfernung:',
            notProvided: 'Nicht angegeben',
            priceExVat: 'Preis exkl. MwSt:',
            vat: 'MwSt',
            total: 'Gesamtpreis:',
            autoGenerated: 'Dies ist eine automatisch generierte Quittung.',
            subject: `Quittung für Ihre Fahrt mit Voss Taxi (${req.bookingId})`
          },
          es: {
            title: 'Recibo de su viaje',
            thanks: '¡Gracias por viajar con nosotros!',
            date: 'Fecha del viaje:',
            booking: 'Número de reserva:',
            from: 'Desde:',
            to: 'Hasta:',
            distance: 'Distancia:',
            notProvided: 'No proporcionado',
            priceExVat: 'Precio sin IVA:',
            vat: 'IVA',
            total: 'Precio total:',
            autoGenerated: 'Este es un recibo generado automáticamente.',
            subject: `Recibo de su viaje con Voss Taxi (${req.bookingId})`
          },
          fr: {
            title: 'Reçu pour votre trajet',
            thanks: 'Merci d\'avoir voyagé avec nous !',
            date: 'Date du trajet:',
            booking: 'Numéro de réservation:',
            from: 'De:',
            to: 'À:',
            distance: 'Distance:',
            notProvided: 'Non fourni',
            priceExVat: 'Prix HT:',
            vat: 'TVA',
            total: 'Prix total:',
            autoGenerated: 'Ceci est un reçu généré automatiquement.',
            subject: `Reçu pour votre trajet avec Voss Taxi (${req.bookingId})`
          },
          nn: {
            title: 'Kvittering for turen din',
            thanks: 'Takk for at du reiste med oss!',
            date: 'Dato for tur:',
            booking: 'Bookingnummer:',
            from: 'Frå:',
            to: 'Til:',
            distance: 'Distanse:',
            notProvided: 'Ikkje oppgjeve',
            priceExVat: 'Pris utan MVA:',
            vat: 'MVA',
            total: 'Totalpris:',
            autoGenerated: 'Dette er ei automatisk generert kvittering.',
            subject: `Kvittering for turen din med Voss Taxi (${req.bookingId})`
          }
        }[lang] || { title: 'Kvittering for din tur', thanks: 'Takk for at du reiste med oss!', date: 'Dato for tur:', booking: 'Bookingnummer:', from: 'Fra:', to: 'Til:', distance: 'Distanse:', notProvided: 'Ikke oppgitt', priceExVat: 'Pris uten MVA:', vat: 'MVA', total: 'Totalpris:', autoGenerated: 'Dette er en automatisk generert kvittering.', subject: `Kvittering for din tur med Voss Taxi (${req.bookingId})` };

        // Build HTML receipt matching PDF design
        const formatNOK = (amount: number) => {
          return (amount / 100).toLocaleString(lang === 'no' || lang === 'nn' ? 'no-NO' : lang === 'en' ? 'en-US' : 'de-DE', {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
          });
        };

        const startTime = new Date(receiptData.startDateTime).toLocaleTimeString('no-NO', { hour: '2-digit', minute: '2-digit' });
        const endTime = new Date(receiptData.endDateTime).toLocaleTimeString('no-NO', { hour: '2-digit', minute: '2-digit' });
        const receiptDate = new Date(receiptData.startDateTime).toLocaleDateString('no-NO', { weekday: 'long', year: 'numeric', month: '2-digit', day: '2-digit' });

        const htmlContent = `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { font-family: 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background: #f0f0f0; padding: 20px; }
              .receipt { max-width: 680px; margin: 0 auto; background: white; }
              .header { background: #1a2332; border-radius: 16px 16px 0 0; padding: 24px 30px; display: flex; justify-content: space-between; align-items: flex-start; color: white; }
              .header-left h1 { font-size: 36px; font-weight: bold; margin-bottom: 8px; }
              .header-left h1 .yellow { color: #fbbf24; }
              .header-left p { font-size: 12px; opacity: 0.8; }
              .header-right { text-align: right; }
              .badge { background: #fbbf24; color: #1a2332; padding: 8px 16px; border-radius: 20px; font-weight: 600; font-size: 12px; display: inline-block; margin-bottom: 8px; }
              .receipt-no { font-size: 24px; font-weight: bold; margin-bottom: 4px; }
              .receipt-date { font-size: 12px; opacity: 0.8; }
              .amount-box { background: #f5f5f5; padding: 20px 30px; display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #e5e5e5; }
              .amount-label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
              .amount-value { font-size: 32px; font-weight: bold; color: #1a2332; }
              .time-range { font-size: 14px; color: #1a2332; }
              .columns { display: flex; padding: 20px 30px; gap: 30px; border-bottom: 1px solid #e5e5e5; }
              .column { flex: 1; }
              .column-title { font-size: 12px; font-weight: bold; text-transform: uppercase; color: #1a2332; margin-bottom: 12px; display: flex; align-items: center; gap: 4px; }
              .column-title::before { content: '●'; color: #fbbf24; }
              .column-row { display: flex; margin-bottom: 8px; font-size: 13px; }
              .column-label { color: #666; width: 50px; }
              .column-value { color: #1a2332; flex: 1; }
              .table-section { padding: 20px 30px; border-bottom: 1px solid #e5e5e5; }
              .table-title { font-size: 14px; font-weight: bold; color: #1a2332; margin-bottom: 12px; }
              table { width: 100%; border-collapse: collapse; font-size: 13px; }
              th { text-align: left; padding: 8px 0; border-bottom: 1px solid #ddd; font-weight: 600; color: #666; text-transform: uppercase; font-size: 11px; }
              td { padding: 8px 0; border-bottom: 1px solid #f0f0f0; }
              tr:hover { background: #f9f9f9; }
              tr.total td { background: #fef3c7; font-weight: bold; border-top: 2px solid #fbbf24; padding-top: 12px; }
              .footer-section { padding: 20px 30px; display: flex; justify-content: space-between; border-bottom: 1px solid #e5e5e5; font-size: 13px; }
              .footer-item { text-align: center; flex: 1; }
              .footer-label { color: #666; font-size: 11px; text-transform: uppercase; margin-bottom: 4px; }
              .footer-value { font-weight: bold; font-size: 16px; color: #1a2332; }
              .final-total { padding: 20px 30px; text-align: right; font-size: 14px; }
              .final-label { color: #666; }
              .final-value { font-size: 24px; font-weight: bold; color: #1a2332; }
              .bottom-note { background: #f5f5f5; padding: 16px 30px; text-align: center; font-size: 11px; color: #999; border-radius: 0 0 16px 16px; }
            </style>
          </head>
          <body>
            <div class="receipt">
              <!-- Header -->
              <div class="header">
                <div class="header-left">
                  <h1><span class="yellow">Voss</span><br><span class="yellow">Taxi</span></h1>
                  <p>Tlf. 56 51 13 40 | Org.nr: ${receiptData.vatRegistrationNo || '970 148 642 MVA'}</p>
                </div>
                <div class="header-right">
                  <div class="badge">KVITTERING</div>
                  <div class="receipt-no">#${receiptData.receiptNo}</div>
                  <div class="receipt-date">${receiptDate}</div>
                </div>
              </div>

              <!-- Amount Box -->
              <div class="amount-box">
                <div>
                  <div class="amount-label">Betalt</div>
                  <div class="amount-value">${formatNOK(receiptData.total || 0)} kr</div>
                </div>
                <div class="time-range">${startTime} - ${endTime}</div>
              </div>

              <!-- Two Columns -->
              <div class="columns">
                <div class="column">
                  <div class="column-title">Turdetaljar</div>
                  <div class="column-row">
                    <div class="column-label">Frå</div>
                    <div class="column-value">${receiptData.fromAddress ? receiptData.fromAddress.split(',')[0].trim() : 'Ikkje oppgitt'}</div>
                  </div>
                  <div class="column-row">
                    <div class="column-label">Til</div>
                    <div class="column-value">${receiptData.toAddress ? receiptData.toAddress.split(',')[0].trim() : 'Ikkje oppgitt'}</div>
                  </div>
                  <div class="column-row">
                    <div class="column-label">Tot.km</div>
                    <div class="column-value">${receiptData.km} km</div>
                  </div>
                  <div class="column-row">
                    <div class="column-label">Konto</div>
                    <div class="column-value">1011</div>
                  </div>
                </div>

                <div class="column">
                  <div class="column-title">Reisegrunnlag</div>
                  <div class="column-row">
                    <div class="column-label">Løyve</div>
                    <div class="column-value">${receiptData.licenseNo || '-'}</div>
                  </div>
                  <div class="column-row">
                    <div class="column-label">Førarkort</div>
                    <div class="column-value">${receiptData.licenseNo || '-'}</div>
                  </div>
                  <div class="column-row">
                    <div class="column-label">Leyveid</div>
                    <div class="column-value">${receiptData.receiptNo}</div>
                  </div>
                  <div class="column-row">
                    <div class="column-label">Klient</div>
                    <div class="column-value">${req.email ? req.email.split('@')[0] : 'Privat'}</div>
                  </div>
                </div>
              </div>

              <!-- Specification Table -->
              <div class="table-section">
                <div class="table-title">Spesifikasjon</div>
                <table>
                  <thead>
                    <tr>
                      <th>Takst</th>
                      <th>Type</th>
                      <th>Grunnlag</th>
                      <th>KM</th>
                      <th>Tid</th>
                      <th style="text-align: right;">KR</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Start</td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td style="text-align: right;">0,00</td>
                    </tr>
                    <tr>
                      <td>Kjøreleie</td>
                      <td></td>
                      <td>${receiptData.km} km</td>
                      <td>${receiptData.km}</td>
                      <td></td>
                      <td style="text-align: right;">${formatNOK(receiptData.vatBasis || 0)}</td>
                    </tr>
                    <tr class="total">
                      <td colspan="5">Totalt</td>
                      <td style="text-align: right;">${formatNOK(receiptData.total || 0)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <!-- Footer Summary -->
              <div class="footer-section">
                <div class="footer-item">
                  <div class="footer-label">MVA 12,00%</div>
                  <div class="footer-value">${formatNOK(receiptData.vat || 0)} kr</div>
                </div>
                <div class="footer-item">
                  <div class="footer-label">Grunnlag</div>
                  <div class="footer-value">${formatNOK(receiptData.vatBasis || 0)} kr</div>
                </div>
              </div>

              <!-- Final Total -->
              <div class="final-total">
                <div class="final-label">Total:</div>
                <div class="final-value">${formatNOK(receiptData.total || 0)} kr</div>
              </div>

              <!-- Bottom Note -->
              <div class="bottom-note">
                Modernisert design/utskrift - data hentet frå taksiapparat
              </div>
            </div>
          </body>
          </html>
        `;

        const mailOptions = {
          from: process.env.SMTP_FROM || 'no-reply@vosstaxi.no',
          to: req.email,
          subject: t.subject,
          html: htmlContent,
        };

        await transporter.sendMail(mailOptions);
        
        // Update DB
        const updateStmt = db.prepare(`UPDATE receipt_requests SET status = 'sent' WHERE id = ?`);
        updateStmt.run(req.id);
        
        sent++;
        console.log(`✅ Sent receipt to ${req.email} for booking ${req.bookingId}`);

      } catch (err) {
        console.error(`❌ Failed to process receipt for booking ${req.bookingId}:`, err);
      }
    }

    return NextResponse.json({ message: 'Processed', processed, sent });
  } catch (error) {
    console.error('CRON ERROR:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
