import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import db from '@/lib/db';
const API_BASE = 'https://api.taxi4u.cab';

async function getAuthToken(): Promise<string> {
  const loginResponse = await fetch(`${API_BASE}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      userId: process.env.TAXI4U_USERNAME,
      password: process.env.TAXI4U_PASSWORD,
    }),
  });

  if (!loginResponse.ok) {
    throw new Error(`Auth failed: ${loginResponse.status}`);
  }

  const loginData = await loginResponse.text();
  return loginData.replace(/['"]+/g, '');
}
export async function GET() {
  try {
    // 1. Get all pending receipt requests
    const stmt = db.prepare(`SELECT * FROM receipt_requests WHERE status = 'pending'`);
    const pendingRequests = stmt.all() as {
      id: number;
      bookingId: string;
      email: string;
      language: string;
      status: string;
      timestamp: number;
    }[];

    if (pendingRequests.length === 0) {
      return NextResponse.json({ message: 'No pending receipts' });
    }

    const authToken = await getAuthToken();
    let processed = 0;
    let sent = 0;

    // Set up nodemailer transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || '',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER || '',
        pass: process.env.SMTP_PASS || '',
      },
    });

    for (const req of pendingRequests) {
      processed++;
      try {
        // We use centralCode=VS, you might want this configurable
        const centralCode = 'VS';
        const url = `${API_BASE}/api/receipt?centralCode=${centralCode}&bookRef=${req.bookingId}`;
        
        const response = await fetch(url, {
          headers: {
            'Authorization': `Bearer ${authToken}`
          }
        });

        if (response.status === 404) {
          // Trip not completed or receipt not ready yet
          console.log(`Receipt not ready yet for booking: ${req.bookingId}`);
          continue;
        }

        if (!response.ok) {
          console.error(`Error fetching receipt for ${req.bookingId}: ${response.status}`);
          continue;
        }

        const receiptData = await response.json();
        
        const lang = req.language || 'no';
        const t = {
          no: {
            title: 'Kvittering for din tur',
            thanks: 'Takk for at du reiste med oss!',
            date: 'Dato for tur:',
            booking: 'Bookingnummer:',
            from: 'Fra:',
            to: 'Til:',
            distance: 'Distanse:',
            notProvided: 'Ikke oppgitt',
            priceExVat: 'Pris uten MVA:',
            vat: 'MVA',
            total: 'Totalpris:',
            autoGenerated: 'Dette er en automatisk generert kvittering.',
            subject: `Kvittering for din tur med Voss Taxi (${req.bookingId})`
          },
          en: {
            title: 'Receipt for your trip',
            thanks: 'Thank you for traveling with us!',
            date: 'Trip date:',
            booking: 'Booking number:',
            from: 'From:',
            to: 'To:',
            distance: 'Distance:',
            notProvided: 'Not provided',
            priceExVat: 'Price ex. VAT:',
            vat: 'VAT',
            total: 'Total price:',
            autoGenerated: 'This is an automatically generated receipt.',
            subject: `Receipt for your trip with Voss Taxi (${req.bookingId})`
          },
          de: {
            title: 'Quittung für Ihre Fahrt',
            thanks: 'Danke, dass Sie mit uns gereist sind!',
            date: 'Fahrtdatum:',
            booking: 'Buchungsnummer:',
            from: 'Von:',
            to: 'Nach:',
            distance: 'Entfernung:',
            notProvided: 'Nicht angegeben',
            priceExVat: 'Preis exkl. MwSt:',
            vat: 'MwSt',
            total: 'Gesamtpreis:',
            autoGenerated: 'Dies ist eine automatisch generierte Quittung.',
            subject: `Quittung für Ihre Fahrt mit Voss Taxi (${req.bookingId})`
          },
          es: {
            title: 'Recibo de su viaje',
            thanks: '¡Gracias por viajar con nosotros!',
            date: 'Fecha del viaje:',
            booking: 'Número de reserva:',
            from: 'Desde:',
            to: 'Hasta:',
            distance: 'Distancia:',
            notProvided: 'No proporcionado',
            priceExVat: 'Precio sin IVA:',
            vat: 'IVA',
            total: 'Precio total:',
            autoGenerated: 'Este es un recibo generado automáticamente.',
            subject: `Recibo de su viaje con Voss Taxi (${req.bookingId})`
          },
          fr: {
            title: 'Reçu pour votre trajet',
            thanks: 'Merci d\'avoir voyagé avec nous !',
            date: 'Date du trajet:',
            booking: 'Numéro de réservation:',
            from: 'De:',
            to: 'À:',
            distance: 'Distance:',
            notProvided: 'Non fourni',
            priceExVat: 'Prix HT:',
            vat: 'TVA',
            total: 'Prix total:',
            autoGenerated: 'Ceci est un reçu généré automatiquement.',
            subject: `Reçu pour votre trajet avec Voss Taxi (${req.bookingId})`
          },
          nn: {
            title: 'Kvittering for turen din',
            thanks: 'Takk for at du reiste med oss!',
            date: 'Dato for tur:',
            booking: 'Bookingnummer:',
            from: 'Frå:',
            to: 'Til:',
            distance: 'Distanse:',
            notProvided: 'Ikkje oppgjeve',
            priceExVat: 'Pris utan MVA:',
            vat: 'MVA',
            total: 'Totalpris:',
            autoGenerated: 'Dette er ei automatisk generert kvittering.',
            subject: `Kvittering for turen din med Voss Taxi (${req.bookingId})`
          }
        }[lang] || { title: 'Kvittering for din tur', thanks: 'Takk for at du reiste med oss!', date: 'Dato for tur:', booking: 'Bookingnummer:', from: 'Fra:', to: 'Til:', distance: 'Distanse:', notProvided: 'Ikke oppgitt', priceExVat: 'Pris uten MVA:', vat: 'MVA', total: 'Totalpris:', autoGenerated: 'Dette er en automatisk generert kvittering.', subject: `Kvittering for din tur med Voss Taxi (${req.bookingId})` };

        // Build modern HTML email with professional design
        const formatNOK = (amount: number) => {
          return (amount / 100).toLocaleString(lang === 'no' || lang === 'nn' ? 'no-NO' : lang === 'en' ? 'en-US' : 'de-DE', {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
          });
        };

        const htmlContent = `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
              .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); overflow: hidden; }
              .header { background: linear-gradient(135deg, #1f2937 0%, #111827 100%); color: white; padding: 40px 30px; text-align: center; }
              .header h1 { margin: 0 0 10px 0; font-size: 32px; font-weight: bold; }
              .header p { margin: 0; font-size: 14px; opacity: 0.9; }
              .content { padding: 40px 30px; }
              .status-badge { background: #10b981; color: white; padding: 12px 20px; border-radius: 8px; display: inline-block; margin-bottom: 20px; font-weight: 600; }
              .section { margin-bottom: 30px; }
              .section-title { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px; font-weight: 600; }
              .section-content { background: #f9fafb; padding: 16px; border-radius: 8px; }
              .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
              .row:last-child { border-bottom: none; }
              .label { color: #6b7280; font-size: 14px; }
              .value { color: #1f2937; font-weight: 600; }
              .address-box { background: white; border-left: 4px solid #f59e0b; padding: 12px; margin: 8px 0; }
              .price-section { background: #f3f4f6; padding: 20px; border-radius: 8px; }
              .price-row { display: flex; justify-content: space-between; padding: 10px 0; font-size: 14px; }
              .price-row.total { font-size: 18px; font-weight: bold; color: #1f2937; border-top: 2px solid #e5e7eb; padding-top: 15px; margin-top: 10px; }
              .footer { background: #f9fafb; padding: 30px; text-align: center; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🚕 VOSS TAXI</h1>
                <p>${t.title}</p>
              </div>

              <div class="content">
                <div class="status-badge">✅ ${lang === 'no' || lang === 'nn' ? 'TUR FULLFØRT' : lang === 'en' ? 'TRIP COMPLETED' : lang === 'de' ? 'FAHRT ABGESCHLOSSEN' : lang === 'fr' ? 'TRAJET TERMINÉ' : 'VIAJE COMPLETADO'}</div>

                <div class="section">
                  <div class="section-title">${lang === 'no' || lang === 'nn' ? 'Bookinginformasjon' : lang === 'en' ? 'Booking Information' : lang === 'de' ? 'Buchungsinformationen' : lang === 'fr' ? 'Informations de réservation' : 'Información de reserva'}</div>
                  <div class="section-content">
                    <div class="row">
                      <span class="label">${t.booking}</span>
                      <span class="value">${receiptData.bookRef || req.bookingId}</span>
                    </div>
                    <div class="row">
                      <span class="label">${lang === 'no' || lang === 'nn' ? 'Kjøretøy' : 'Vehicle'}</span>
                      <span class="value">${receiptData.licenseNo || t.notProvided}</span>
                    </div>
                  </div>
                </div>

                <div class="section">
                  <div class="section-title">${t.date}</div>
                  <div class="section-content">
                    <div class="row">
                      <span class="label">${lang === 'no' || lang === 'nn' ? 'Avreise' : lang === 'en' ? 'Departure' : 'Abfahrt'}</span>
                      <span class="value">${new Date(receiptData.startDateTime).toLocaleString(lang === 'no' || lang === 'nn' ? 'no-NO' : lang === 'en' ? 'en-US' : 'de-DE')}</span>
                    </div>
                    <div class="row">
                      <span class="label">${lang === 'no' || lang === 'nn' ? 'Ankomst' : lang === 'en' ? 'Arrival' : 'Ankunft'}</span>
                      <span class="value">${new Date(receiptData.endDateTime).toLocaleString(lang === 'no' || lang === 'nn' ? 'no-NO' : lang === 'en' ? 'en-US' : 'de-DE')}</span>
                    </div>
                  </div>
                </div>

                <div class="section">
                  <div class="section-title">${t.distance}</div>
                  <div style="background: #f9fafb; padding: 16px; border-radius: 8px;">
                    <div style="margin-bottom: 12px;">
                      <div class="label" style="margin-bottom: 4px;">🟢 ${t.from}</div>
                      <div class="address-box">${receiptData.fromAddress || t.notProvided}</div>
                    </div>
                    <div>
                      <div class="label" style="margin-bottom: 4px;">🔴 ${t.to}</div>
                      <div class="address-box">${receiptData.toAddress || t.notProvided}</div>
                    </div>
                    <div class="row" style="margin-top: 16px; padding-top: 16px; border-top: 1px solid #e5e7eb;">
                      <span class="label">${lang === 'no' || lang === 'nn' ? 'Kjørte km' : lang === 'en' ? 'Distance driven' : 'Fahrtdistanz'}</span>
                      <span class="value">${receiptData.km} km</span>
                    </div>
                  </div>
                </div>

                <div class="section">
                  <div class="section-title">${t.priceExVat}</div>
                  <div class="price-section">
                    <div class="price-row">
                      <span>${t.priceExVat}</span>
                      <span>${formatNOK(receiptData.vatBasis || 0)} kr</span>
                    </div>
                    <div class="price-row">
                      <span>${t.vat} (${receiptData.vatPercentage}%)</span>
                      <span>${formatNOK(receiptData.vat || 0)} kr</span>
                    </div>
                    <div class="price-row total">
                      <span>${t.total}</span>
                      <span>${formatNOK(receiptData.total || 0)} kr</span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="footer">
                <p><strong>Voss Taxi</strong></p>
                <p>${lang === 'no' || lang === 'nn' ? 'Org.nr' : 'Org. No'}: ${receiptData.vatRegistrationNo || '970 148 642 MVA'}</p>
                <p>${t.thanks}</p>
                <p style="margin-top: 15px; color: #9ca3af;">${t.autoGenerated}</p>
              </div>
            </div>
          </body>
          </html>
        `;

        const mailOptions = {
          from: process.env.SMTP_FROM || 'no-reply@vosstaxi.no',
          to: req.email,
          subject: t.subject,
          html: htmlContent,
        };

        await transporter.sendMail(mailOptions);
        
        // Update DB
        const updateStmt = db.prepare(`UPDATE receipt_requests SET status = 'sent' WHERE id = ?`);
        updateStmt.run(req.id);
        
        sent++;
        console.log(`✅ Sent receipt to ${req.email} for booking ${req.bookingId}`);

      } catch (err) {
        console.error(`❌ Failed to process receipt for booking ${req.bookingId}:`, err);
      }
    }

    return NextResponse.json({ message: 'Processed', processed, sent });
  } catch (error) {
    console.error('CRON ERROR:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
